name: Build & Push to Docker Hub (Manual)

on:
  workflow_dispatch:   # Manual run only

jobs:
  build_and_push:
    runs-on: self-hosted   # Your self-hosted runner

    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}   # DockerHub username
      IMAGE_NAME: myapp                           # Change to your app name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Print Success Message
        run: echo "Image pushed: $USERNAME/$IMAGE_NAME:latest"
